### ISSUE TITLE
I'm getting OT is not defined

### ISSUE THREAD

**Issue by sureshkoduri** [Mobilea/cordova-plugin-opentokjs-example#1]
Hi, Im trying to implement this plugin. Im getting OT is not defined in my controller. Is there anything to define module?? Please the attachment
![screen shot 2015-08-26 at 5 27 05 pm](https://cloud.githubusercontent.com/assets/5337707/9492714/c1f88bce-4c17-11e5-9c85-10d108bc91f7.png)
 Please help me. I'm struct here.

**Comment by mark-veenstra** [comment]
Please refer to the README: https://github.com/Mobilea/cordova-plugin-opentokjs-example#setup

I quote:
NOTE: Running ionic serve does not include the necessary opentok.js from the plugin. Therefore this command doesn't work to test the application. Use ionic build browser and gulp browser:serve instead.

**Comment by PrimeObjects** [comment]
I ran into the same issue. Question : is opentok.js automatically generated when doing the build? Or where should I get it?
